// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// qrsdet
NumericVector qrsdet(const NumericVector& input);
RcppExport SEXP eplimited_qrsdet(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(qrsdet(input));
    return rcpp_result_gen;
END_RCPP
}
