# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' detect the R-peaks in a ecg signal
#'
#' @param input A numeric vector representing the ecg
#' @return a numeric vector with the indices of the R-peaks
#' @examples data(ecg)
#' plot(ecg, type="l", xlim=c(10*200, 15*200))
#' abline(v = qrsdet(ecg), col=2, lty=2)
qrsdet <- function(input) {
    .Call('eplimited_qrsdet', PACKAGE = 'eplimited', input)
}

